### ISSUE TITLE
Задание №7

### ISSUE THREAD

**Issue by alexey-kozlenkov** [N1kSt4r/ExadelProject#5]
0. На ленте не видно ни описаний, ни лайков, ни авторства, ни даты. Неочевидно, как работать с вашим порталом.
1. Лайки не сохраняются при логауте.
1. Не наблюдаю фильтров вообще, поиск(?) по тегам не работает.
2. `showPhoto` выполнен не очень оптимальным способом, потому что вы производите множество `innerHtml` присвоений. В целом громоздкий метод

**Comment by N1kSt4r** [comment]
0. Стиль Инстаграма примерно такой же, но ведь я не слышал, что его интерфейс не очевиден.
1. Я не знаю, может не та версия, хотя я вроде бы ничего не менял, но вот только что проверил - все сохраняется
2. Немного не понял про фильтры. С поиском согласен, но пока не понимаю почему. На моей стороне работает
3. Может быть, но тогда как сделать лучше? Он до этого создавался динамически - перписал на тэмплэйт, был еще больше - снес в другие функции. Если предложите идею упрощения, то упрощу

**Comment by N1kSt4r** [comment]
2. На самом деле не согласен, т.к. все работает, просто допустил ошибку в хэштэге
![SearchTestHashTag](https://user-images.githubusercontent.com/45687815/56571905-9fc61680-65c6-11e9-838b-e3d47993e0c5.png)
![SearchVladislav](https://user-images.githubusercontent.com/45687815/56571906-a05ead00-65c6-11e9-9266-7aacacf7c283.png)
![logOutUnliked](https://user-images.githubusercontent.com/45687815/56571907-a05ead00-65c6-11e9-9495-f345b26a169c.png)
![logInUnliked](https://user-images.githubusercontent.com/45687815/56571909-a05ead00-65c6-11e9-8b3c-714c574f2844.png)
![logOutLiked](https://user-images.githubusercontent.com/45687815/56571910-a0f74380-65c6-11e9-8f17-0e96a3811cfc.png)
![logInLiked](https://user-images.githubusercontent.com/45687815/56571911-a0f74380-65c6-11e9-8221-38663470c9e4.png)
