### ISSUE TITLE
wrong package name

### ISSUE THREAD

**Issue by akarzhaneuski** [N1kSt4r/ExadelProject#7]
https://github.com/N1kSt4r/ExadelProject/blob/909108c0a68f706bca709424671577e1c804ef15/src/main/java/bsu/ExadelProject/filters/TestFilter.java#L1

Имя пакетов должны быть без camel case.
bsu.ExadelProject => bsu.exadel.project

**Comment by N1kSt4r** [comment]
Исправлено
